# Generated by Django 5.2.12 on 2026-03-08 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('address', models.CharField(max_length=300, verbose_name='direccion')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='barrio/localidad')),
                ('city', models.CharField(default='Buenos Aires', max_length=100, verbose_name='ciudad')),
            ],
            options={
                'verbose_name': 'cine',
                'verbose_name_plural': 'cines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='título')),
                ('original_title', models.CharField(blank=True, default='', max_length=300, verbose_name='título original')),
                ('poster_url', models.URLField(blank=True, default='', verbose_name='URL del póster')),
                ('rating', models.CharField(blank=True, default='', help_text='Ej: ATP, +13, +16, +18', max_length=10, verbose_name='clasificación')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='duración (minutos)')),
            ],
            options={
                'verbose_name': 'película',
                'verbose_name_plural': 'películas',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Ej: 2x1 con tarjeta Santander todos los días', max_length=300, verbose_name='descripción')),
                ('payment_method', models.CharField(blank=True, default='', help_text='Ej: Santander, Ualá, Mercado Pago', max_length=100, verbose_name='medio de pago')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='válida desde')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='válida hasta')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='cartelera.cinema', verbose_name='cine')),
            ],
            options={
                'verbose_name': 'promoción',
                'verbose_name_plural': 'promociones',
            },
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='fecha y hora')),
                ('screen', models.CharField(blank=True, default='', max_length=50, verbose_name='sala')),
                ('format', models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('IMAX', 'IMAX')], default='2D', max_length=10, verbose_name='formato')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='cartelera.cinema', verbose_name='cine')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='cartelera.movie', verbose_name='película')),
            ],
            options={
                'verbose_name': 'función',
                'verbose_name_plural': 'funciones',
                'ordering': ['datetime', 'cinema', 'screen'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de confirmación'), ('confirmed', 'Confirmado'), ('rejected', 'Rechazado')], default='pending', max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='propuesto el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('requested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_requests_received', to=settings.AUTH_USER_MODEL, verbose_name='a quien se propone')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_requests_sent', to=settings.AUTH_USER_MODEL, verbose_name='quien propone')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='cartelera.showtime', verbose_name='función')),
            ],
            options={
                'verbose_name': 'match',
                'verbose_name_plural': 'matches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('looking', 'Buscando compañero'), ('matched', 'Compañero encontrado'), ('cancelled', 'Cancelado')], default='looking', max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='anotado el')),
                ('note', models.CharField(blank=True, default='', help_text='Ej: Solo voy si es versión original', max_length=200, verbose_name='nota opcional')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='cartelera.showtime', verbose_name='función')),
            ],
            options={
                'verbose_name': 'asistencia',
                'verbose_name_plural': 'asistencias',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='showtime',
            constraint=models.UniqueConstraint(fields=('cinema', 'datetime', 'screen'), name='unique_showtime_per_screen'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('user', 'showtime'), name='unique_attendance_per_user_showtime'),
        ),
    ]
